name: Tests
on:
  repository_dispatch:
    types: [tests-report]
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: test:xcc:as
        run: cd cross-contract-as && yarn && yarn test
      - name: test:xcc:rs
        run: cd cross-contract-rs && yarn && yarn test
      - name: test:donation:as
        run: cd donation-as && yarn && yarn test
      - name: test:donation:rs
        run: cd donation-rs && yarn && yarn test
      - name: test:storage:as
        run: cd storage-as && yarn && yarn test
      - name: test:storage:rs
        run: cd storage-rs && yarn && yarn test